# Generated by Django 5.0.6 on 2024-06-12 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_post_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='publish',
        ),
    ]
