# Generated by Django 5.0.6 on 2024-07-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_comment_dislikes_remove_comment_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='No description'),
        ),
    ]
